version:  '3'
services:
  datascience-notebook:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/tmp/working
    ports:
      - 8888:8888
    command: "jupyter notebook --no-browser --allow-root --ip=\"*\" --notebook-dir=/tmp/working"
    working_dir: "/tmp/working"
    container_name: jupyter_notebookKaggle
